### ISSUE TITLE
Why the function get_teweets in term mode don't allow to use the date?

### ISSUE THREAD

**Issue by AritzUMA** [bocchilorenzo/ntscraper#25]
Hi @bocchilorenzo 

Firstly, thank you for your efforts and contributions. I would like to inquire if there is a possibility to scrape tweets between two dates for a specific term or hashtag.

I know that once that we use get_tweets with term mode and we write a date in since, it is deleted. I want to scrape tweets for one day for specific term but not all, only 100. There is not possibility no?

thanks

**Comment by bocchilorenzo** [comment]
You're right, there was a missing check. Now using "since" together with "number" will work correctly.
