### ISSUE TITLE
Error when scrape more than one term inside the term

### ISSUE THREAD

**Issue by AritzUMA** [bocchilorenzo/ntscraper#26]
Hi community?

I am trying to scrape tweets in term mode and I get a Empty page when I try to scrape information with withspaces like "PNV y Junts" that is a trendic topic now in Spain. 

Fetching data:  60%|███████████████████████████████████████                          | 30/50 [25:36<14:31, 43.56s/user]First Attempt for termino: PNV y Junts
12-Nov-23 20:17:48 - Empty page on https://nitter.ktachibana.party. Trying https://nitter.uni-sonia.com
12-Nov-23 20:17:54 - Empty page on https://nitter.uni-sonia.com. Trying https://nitter.perennialte.ch
12-Nov-23 20:17:58 - Empty page on https://nitter.perennialte.ch. Trying https://nitter.privacydev.net
12-Nov-23 20:18:04 - Empty page on https://nitter.privacydev.net. Trying https://nitter.d420.de
12-Nov-23 20:18:09 - Empty page on https://nitter.d420.de. Trying https://nitter.tinfoil-hat.net
High number of retries detected. Testing all instances...
Testing instances: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [02:04<00:00,  4.43s/it]
New working instances: https://nitter:nitter@nitter.nixnet.services█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [02:04<00:00,  4.07s/it]
High number of retries detected. Testing all instances...
Testing instances: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [01:57<00:00,  4.18s/it]
New working instances: https://nitter:nitter@nitter.nixnet.services█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [01:57<00:00,  3.97s/it]

**Comment by bocchilorenzo** [comment]
You're right, there was an issue with the escaping of the term's allowed characters.
