### ISSUE TITLE
Search for tweets that mention a particular handle

### ISSUE THREAD

**Issue by eekom-research** [bocchilorenzo/ntscraper#27]
Hello, 
If I try to search for tweets that mention a specific username, for example, `github_hash_tweets = scraper.get_tweets("@github", mode='term')`, it still shows mostly entries mentioning the term 'github', which is not what I want. Is there an option or workflow where I can get tweets tweeted **to** a particular user?

**Comment by bocchilorenzo** [comment]
Right now there is no way to apply this type of filtering. I'll add it in future versions.

**Comment by psegovias** [comment]
> Hello, If I try to search for tweets that mention a specific username, for example, `github_hash_tweets = scraper.get_tweets("@github", mode='term')`, it still shows mostly entries mentioning the term 'github', which is not what I want. Is there an option or workflow where I can get tweets tweeted **to** a particular user?

Did you try with operator 'to:'

`github_hash_tweets = scraper.get_tweets("to:github", mode='term')`

**Comment by bocchilorenzo** [comment]
I've added all the filters in Nitter, plus the "to" and "lang" filters that were discussed here in the issues. Simply add `to="username"` to the `get_tweets` call to use it.
