### ISSUE TITLE
date limits are not working well

### ISSUE THREAD

**Issue by bnorambuenay** [bocchilorenzo/ntscraper#30]
Hi,

First of all, thank you so much for the package, it's amazing.
I have been using it since yesterday, and I realized that when you enter **since** and/or **until** dates (in the correct format YYYY-MM-DD), the scraper does not work as expected (it searches tweets, but finds and extracts just a little amount). 
As an example, look what happens when I search for term "musk" with and without date restrictions:

**with**:
![Screenshot 2023-11-15 at 12 33 44](https://github.com/bocchilorenzo/ntscraper/assets/65251793/dea37cc0-90a7-43a0-810f-9a933ec8feb7)

**without**:
![Screenshot 2023-11-15 at 12 32 57](https://github.com/bocchilorenzo/ntscraper/assets/65251793/76041a81-b53a-4694-a1e8-49ef4808bf30)

I also realized that when I do not set a "number" parameter, the scraper fails:
![Screenshot 2023-11-15 at 12 38 20](https://github.com/bocchilorenzo/ntscraper/assets/65251793/c1156b45-1f77-4a48-b254-ef6cc7413d2c)

Do you know what could be the problem and how to fix it?

**Comment by thelollipopka** [comment]
Same problem here.

**Comment by selihadji** [comment]
Hello, I would like to reopen this issue because I have the same problem. Could you please fix it again?
