### ISSUE TITLE
Search Term always returns empty page if multiple words.

### ISSUE THREAD

**Issue by steeljardas** [bocchilorenzo/ntscraper#34]
So for example, if I manually search "CEX Listing" in Nitter it shows a bunch of tweets as normal, but if I try that with ntscraper it just says it returns a blank page using the default mode (term).

If I just do "CEX" or "Listing" it works perfectly fine so I don't think this is intended?

**Comment by bocchilorenzo** [comment]
Hi, I just tested that but it returns 4 results like it does on the Nitter website. Perhaps the issue could be due to the instance not being updated, let me know if it does it again.
![immagine](https://github.com/bocchilorenzo/ntscraper/assets/34674329/6589da7e-dc9a-440b-abe4-c60d41a088b7)
