### ISSUE TITLE
How to add own localhost working instance?

### ISSUE THREAD

**Issue by NetworkWebMasters** [bocchilorenzo/ntscraper#35]
ntscraper is working perfectly.

I just want to add my own localhost instance url is "http://localhost" and i want to skip checking process of all instance.

How can i add this?

Can you suggest python code example?

**Comment by bocchilorenzo** [comment]
Now it works, I had yet to implement it when I wrote it in the readme.

**Comment by abdulmoiz-ds** [comment]
I am facing error Error is : TypeError: Nitter.init() got an unexpected keyword argument 'skip_instance_check'. How to solve it?
