### ISSUE TITLE
How to disable testing instances?

### ISSUE THREAD

**Issue by DanRev111212** [bocchilorenzo/ntscraper#36]
Module is working all dandy but, but how do I disable testing instances? It keeps taking longer and I have to modify my code a couple of times. Kind of gets annoying.

**Comment by bocchilorenzo** [comment]
Hi, you can do that by using the parameter `skip_instance_check` when initializing the scraper. Like so:
`scraper = Nitter(log_level=1, skip_instance_check=True)`
