### ISSUE TITLE
All Instances Down? "Max retries reached. Check your request and try again"

### ISSUE THREAD

**Issue by muenze8** [bocchilorenzo/ntscraper#4]
Hello,

I am not sure where this issue comes from, is it nitter side or ntscraper's, but a script that I have had running for over a week (runs every 15 minutes to get tweets matching criteria) has just stopped, and now showing the below message in every run.
"Max retries reached. Check your request and try again"

Any thoughts?

**Comment by bocchilorenzo** [comment]
It seems Twitter has temporarily blocked all anonymous requests as seen in [this Nitter issue](https://github.com/zedeus/nitter/issues/919). For now every instance has the same issues even in the browser, hopefully they will re-enable anonymous access soon.

**Comment by muenze8** [comment]
> It seems Twitter has temporarily blocked all anonymous requests as seen in [this Nitter issue](https://github.com/zedeus/nitter/issues/919). For now every instance has the same issues even in the browser, hopefully they will re-enable anonymous access soon.

Hello
So Nitter is back up again, but ntscripper is buggy somehow. Sometimes it works and sometimes it doesn't.
Did you notice any changes in the structure of Nitter?

Thanks!

**Comment by bocchilorenzo** [comment]
I've updated the automatic instance selection to only include updated instances, so older and broken instances will be excluded from now on.
