### ISSUE TITLE
How to get the retweets username or quotes username of a tweet

### ISSUE THREAD

**Issue by ybxgood** [bocchilorenzo/ntscraper#41]
I want to get the retweets username or quotes username of a tweet. Please tell me how to achieve it. Thank you very much.

**Comment by bocchilorenzo** [comment]
Hello, as I've said in the other issue, the username of the user that made a retweet is not possible to extract at the moment due to it not being included on the webpage. For the quoted tweet, the information is contained for each tweet in the attribute 'quoted-post'.
