### ISSUE TITLE
Tweets Scraping Status

### ISSUE THREAD

**Issue by sujayrittikar** [bocchilorenzo/ntscraper#43]
- If a user's tweets weren't scraped or were not available between provided timestamps, it should return either an empty list of tweets or some unique response and not throw IndexError / NoneType.
- If a user's account is suspended, the scraper should return some sort of a unique response.
- Similarly, if a user has locked their account?
- Some users take forever to be scraped, can you add some sort of a waiting time limit?

This can enable anyone to track the status of scraping tweets easily and have a better control.

**Comment by bocchilorenzo** [comment]
Hi, thanks for the issue. Regarding the first point, the library now always returns the same object regardless of whether the page is empy or not. If there is an error shown on the page, like "user is suspended" or "page not found", the error will now be printed in the terminal. Regarding your last point, the speed depends on the speed of the instance and how many tweets there are on the page. The first one can be solved by using a locally hosted instance, while the second can be limited by setting a maximum number of tweets to be scraped.
