### ISSUE TITLE
Error in getting information from Nitter instances

### ISSUE THREAD

**Issue by redfalcoon** [bocchilorenzo/ntscraper#5]
Hi!

starting from today the scraping doesn't work correctly returning the error messages:
Traceback (most recent call last):
  File "CrawlerNitter.py", line 7, in <module>
    user_information = scraper.get_profile_info(user)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 587, in get_profile_info
    is_encrypted = self.__is_instance_encrypted(instance)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 43, in __is_instance_encrypted
    instance_new, soup = self.__get_page("/Twitter", instance)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 106, in __get_page
    if soup.find_all("div", class_="show-more")[-1].find("a").text == "Load newest":
IndexError: list index out of range

this happens using:
user_information = scraper.get_profile_info(user)
but also using:
user_tweets = scraper.get_tweets(user, mode='user', number=posts)

until yesterday the process of crawling worked fine. 
The instance used for the test was the https://nitter.net (the most recent updated) with Version [2023.07.24-20b5cce]

Any suggestion?

Thanks

**Comment by muenze8** [comment]
Hello

I am having the same issue. Nitter UI returns resutls for the queries I am passing in the code, but the ntscraper keeps showing "error fetching from instances" .... and yes, passing the same search query into twitter doesn't return anything too!!

<img width="489" alt="image" src="https://github.com/bocchilorenzo/ntscraper/assets/17484560/e9483e7f-7af8-4539-9af9-f2097b2ff37a">

**Comment by psegovias** [comment]
Twitter operator OR & AND are broken, but i cant identify who this broke the scraper.

**Comment by psegovias** [comment]
I found the error, incoming pull request @redfalcoon @muenze8

**Comment by redfalcoon** [comment]
Patricio,

using your patch the 
user_information = scraper.get_profile_info(user) 
works fine,  not all for 
user_tweets = scraper.get_tweets(user, mode='user', number=posts)
that generate the same error.

Thanks

**Comment by psegovias** [comment]
@redfalcoon  paste your code to try replicate in my env.

**Comment by psegovias** [comment]
i got the same result with user='elonmusk' then i try user='jack' and success.

{
    "image": "https://pbs.twimg.com/profile_images/1661201415899951105/azNjKOSH_400x400.jpg",
    "name": "jack",
    "username": "@jack",
    "id": "12",
    "bio": "#bitcoin and chill.\n\n#nostr: npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m",
    "location": "",
    "website": "https://primal.net/jack",
    "joined": "8:50 PM - 21 Mar 2006",
    "stats": {
        "tweets": 29315,
        "following": 4658,
        "followers": 6523202,
        "likes": 35955,
        "media": 2917
    }
}
27-Jul-23 10:49:22 - Empty profile on http://localhost, trying another random instance
27-Jul-23 10:49:23 - Error fetching https://nitter.onthescent.xyz/, trying another random instance
27-Jul-23 10:49:25 - Error fetching https://twitter.owacon.moe, trying another random instance
{
    "tweets": [
        {
            "link": "https://twitter.com/sza/status/1684461977647845377#m",
            "text": "DND: a lifestyle",
            "user": {
                "name": "SZA",
                "username": "@sza",
                "avatar": "https://pbs.twimg.com/profile_images/1600953582605328384/t5skIcVh_bigger.jpg"
            },
            "date": "Jul 27, 2023 \u00b7 7:13 AM UTC",
            "is-retweet": true,
            "external-link": "",
            "quoted-post": {},
            "stats": {
                "comments": 0,
                "retweets": 20415,
                "quotes": 0,
                "likes": 42522
            },
            "pictures": [],
            "videos": [],
            "gifs": []
        },
        {
            "link": "https://twitter.com/lilyallen/status/1684338954550616069#m",
            "text": "The world really did a number on Sinead O\u2019Oconnor. RIP Angel.",
            "user": {
                "name": "Lily Allen",
                "username": "@lilyallen",
                "avatar": "https://pbs.twimg.com/profile_images/1562055589584404483/C5v4nJvC_bigger.jpg"
            },
            "date": "Jul 26, 2023 \u00b7 11:04 PM UTC",
            "is-retweet": true,
            "external-link": "",
            "quoted-post": {},
            "stats": {
                "comments": 158,
                "retweets": 623,
                "quotes": 0,
                "likes": 17847
            },
            "pictures": [],
            "videos": [],
            "gifs": []
        },
        {
            "link": "https://twitter.com/jack/status/1684455493333557251#m",
            "text": "https://piped.video/watch?v=DOiDUbaBL9E",
            "user": {
                "name": "jack",
                "username": "@jack",
                "avatar": "https://pbs.twimg.com/profile_images/1661201415899951105/azNjKOSH_bigger.jpg"
            },
            "date": "Jul 27, 2023 \u00b7 6:47 AM UTC",
            "is-retweet": false,
            "external-link": "",
            "quoted-post": {},
            "stats": {
                "comments": 90,
                "retweets": 179,
                "quotes": 0,
                "likes": 880
            },
            "pictures": [],
            "videos": [],
            "gifs": []
        },etc....

**Comment by psegovias** [comment]
it could be something related to the instance and not to the scraper

**Comment by bocchilorenzo** [comment]
Thanks @psegovias , just pulled your request. I also think there are some issues with some instances. For example, the nitter,tokhmi.xyz instance is having issues right now as seen here:
![immagine](https://github.com/bocchilorenzo/ntscraper/assets/34674329/6fcd2747-3903-4b61-846f-60c93020d19f)

Closing the issue for now.
