### ISSUE TITLE
 Fetching error: Instance has been rate limited.Use another instance or try again later.

### ISSUE THREAD

**Issue by AritzUMA** [bocchilorenzo/ntscraper#56]
Hi,

I'm attempting to scrape multiple tweets to a user with me 'term' mode, and consistently encountering the same message after retrieving some tweets.

 Fetching error: Instance has been rate limited.Use another instance or try again later.

 The main issue is that the Nitter scraper function doesn't seamlessly switch to another instance; instead, it stops entirely.

**Comment by bocchilorenzo** [comment]
Hi, I'm sorry but the nitter project has been declared as dead by its creator and right now most instances are having issues and will probably start to slowly shut down.

**Comment by AritzUMA** [comment]
There will be alternative to scrape with another front-end method?

**Comment by bocchilorenzo** [comment]
It depends if a new workaround is found. As far as i know, all the current methods rely on guest accounts, but now that those are gone they all broke.
