### ISSUE TITLE
ImportError: cannot import name 'Nitter' from partially initialized module 'ntscraper' (most likely due to a circular import)

### ISSUE THREAD

**Issue by alimehboob955** [bocchilorenzo/ntscraper#64]
ImportError: cannot import name 'Nitter' from partially initialized module 'ntscraper' (most likely due to a circular import)

**Comment by Nirator78** [comment]
Hello,

What's the name of you python file ?

**Comment by bocchilorenzo** [comment]
Hi, sorry for the late reply. This probably happens because your file where you are using ntscraper is also named nitter.py, so it tries to import itself.
