### ISSUE TITLE
missing tweets

### ISSUE THREAD

**Issue by dissizcark** [bocchilorenzo/ntscraper#69]
Hello,

I can pull user's tweets. But it doesn't pull reply tweets.

When I examine the Nitter.py file, it sends a request to https://nitter.poast.org/username. Why don't we post this as https://nitter.poast.org/username/with_replies? So we can get the answers? I tried, but when it happens like this, the server rejects the request. What do you think is the problem?
![Ekran Alıntısı](https://github.com/bocchilorenzo/ntscraper/assets/17483627/8816b2b3-7757-47ed-85e2-68014b9bdf52)

**Comment by bocchilorenzo** [comment]
Hi, I've added the possibility to also get the replies with a "replies" parameter. Regarding the issue you're having with the .poast.org instance, they have a browser check to avoid bots and scrapers, so it cannot be used.
