### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by lucabased** [bocchilorenzo/ntscraper#77]
How about you guys stop abusing my instance? 😭

**Comment by bocchilorenzo** [comment]
Aside from asking people to use their own instance, I can't do anything to stop them from using a public website. Besides, I've tried using your instance to scrape and it was immediately rate limited:
![Immagine](https://github.com/user-attachments/assets/df92bc40-8d9c-41d8-ae8c-548b32306660)

If you need help, you could try asking the guy that runs the poast instance. It seems that when loading the site it runs a script to stop bots.
